### ISSUE TITLE
Typo in Get-BrowserData.ps1

### ISSUE THREAD

**Issue by freycook0** [rvrsh3ll/Misc-Powershell-Scripts#3]
There's a typo in Get-BrowserData.ps1, in the function Get-ChromeBookmarks.  The Json object created to hold the Chrome bookmarks lists the browser as 'Firefox', when it should be 'Chrome'.
![capture](https://user-images.githubusercontent.com/3630589/40061872-89402dca-581f-11e8-8650-a6ec10d3a1c0.PNG)

**Comment by rvrsh3ll** [comment]
Thanks!
