### ISSUE TITLE
Powershell issue

### ISSUE THREAD

**Issue by Clampco** [rvrsh3ll/Misc-Powershell-Scripts#6]
Hello, 
Sorry, I am very new to PowerShell. I need this program to remotely check users browsing history at work.  I can't seem to get the PowerShell script to work. I saved it as a .ps1 extension but all I get is a blank PowerShell terminal.

Thank you, considering this is probably user error.

**Comment by J0rtIT** [comment]
The problem is that you want to get the information from a remote computer using a single script, this script would require adaptation, but in short, this would be the answer:

```Powershell
$username ="your domain login" #2 
$Password= "ThePassword" #domain admin pwd
$UserCredential = New-Object pscredential -ArgumentList $username, (  ConvertTo-SecureString -String $Password -AsPlainText -Force)
$computers = Get-ADComputer  -Filter * | where{ $_.Enabled -eq $true}

Invoke-Command -ComputerName $Computer -Credential $UserCredential -ScriptBlock $(Get-content .\thisscript.ps1)
```

**Comment by Clampco** [comment]
Thank you for your response. I'm still not sure what's wrong. when I run the script I just get a blank screen and it closes out. I hope I put your commands in the right place.

**Comment by J0rtIT** [comment]
Yes because the $computer var is empty  

```powershell
$username ="your domain login" #2 
$Password= "ThePassword" #domain admin pwd
$UserCredential = New-Object pscredential -ArgumentList $username, (  ConvertTo-SecureString -String $Password -AsPlainText -Force)
$computers = Get-ADComputer  -Filter * | where{ $_.Enabled -eq $true}

foreach($computer in $computers){
    Invoke-Command -ComputerName $Computer -Credential $UserCredential -ScriptBlock $(Get-content .\thisscript.ps1)
}
```

**Comment by Clampco** [comment]
I'm sorry I'm a noob with power shell. Where does $computer var go? It's very obvious where the domain login goes, but I'm unsure about the computer name.

**Comment by J0rtIT** [comment]
Computers are filled using the active directory cmdlet Get-adcomputer on the domain controller :)
