### ISSUE TITLE
Date information

### ISSUE THREAD

**Issue by joaosperotto** [rvrsh3ll/Misc-Powershell-Scripts#7]
First of all, thanks for the script, it`s working properly.

Second, I would like to know your thoughts on how to get the Date, Hour and the exact link where which website was visited. Just like in the Browser history tab.
![image](https://user-images.githubusercontent.com/32466418/59937613-4d1fa400-9429-11e9-85be-523b76cba48e.png)

**Comment by rvrsh3ll** [comment]
Depends on what browser your targeting. Firefox would require further parsing of the sqlite database. You would have to extend this script to use a library such as https://github.com/RamblingCookieMonster/PSSQLite
